spring.application.name=btgpactual

# AWS DynamoDB
aws.region=us-east-1
aws.dynamodb.endpoint=http://localhost:8000

# DynamoDB table names
aws.dynamodb.table.clients=Clients
aws.dynamodb.table.funds=Funds
aws.dynamodb.table.transactions=Transactions
aws.dynamodb.table.subscriptions=Subscriptions
aws.dynamodb.table.users=Users

# JWT
jwt.secret=btgpactual-super-secret-key-for-jwt-token-signing-256bits!!
jwt.expiration-ms=3600000

logging.level.org.springframework.web=INFO
logging.level.software.amazon.awssdk=DEBUG