spring.application.name=btgpactual

# AWS LocalStack
aws.region=us-east-1
aws.dynamodb.endpoint=http://localhost:4566
aws.ses.endpoint=http://localhost:4566
aws.sns.endpoint=http://localhost:4566
aws.ses.from=noreply@btgpactual.com

# JWT
jwt.secret=btgpactual-super-secret-key-for-jwt-token-signing-256bits!!
jwt.expiration-ms=3600000

logging.level.org.springframework.web=INFO
logging.level.software.amazon.awssdk=DEBUG
